### ISSUE TITLE
Compatability with old HDHR hardware?

### ISSUE THREAD

**Issue by sengsational** [collinturney/plugin.video.hdhomerun#1]
Is this package compatible with the original HDHR hardware (HDHR-US and HDHR3-US)?

**Comment by collinturney** [comment]
Unfortunately at the moment I only have an HDHR4 so I can't test that out. However, it should be compatible with any HDHR that supports their documented REST API and auto discovery.

https://www.silicondust.com/hdhomerun/hdhomerun_http_development.pdf

https://my.hdhomerun.com
